export const departments = [
  "Arabic Language and Literature",
  "Anthropology",
  "Art History",
  "Asian Studies",
  "Bible Class",
  "Biology",
  "Business Administration",
  "Cinema Culture",
  "Cognitive Sciences",
  "Communications",
  "Community Mental Health",
  "Comparative Literature",
  "Computer Science",
  "Counseling and Human Development",
  "Creative Arts",
  "Criminology",
  "Data and Cyber Science Cluster",
  "Digital Communication Cluster - Practical",
  "Economics",
  "English Language and Literature",
  "English Studies for Academic and International Purposes",
  "Evolutionary and Environmental Biology",
  "Faculty of Law",
  "For Maritime Civilizations",
  "General History",
  "Geography and Environmental Studies",
  "Geomarine Sciences",
  "Gerontology-Sciences of Aging",
  "Germany and Modern Europe Curriculum",
  "Hebrew and Comparative Literature",
  "Hebrew Class",
  "Human Biology",
  "Human Resources Cluster",
  "Human Services",
  "Humanities Cluster",
  "Information and Knowledge Management",
  "Information Systems",
  "Innovation and Entrepreneurship Cluster",
  "International School",
  "Israel Studies",
  "Language Studies",
  "Leadership and Policy in Education",
  "Learning and Teaching Sciences",
  "Learning Disabilities",
  "Marine Biology",
  "Marine Technologies",
  "Mathematical Education",
  "Mathematics",
  "Medical Imaging Sciences",
  "Medical Sciences",
  "Middle Eastern and Islamic Studies",
  "Museology",
  "Music",
  "Natural Resources and Environment Management",
  "Nursing",
  "Occupational Therapy",
  "Ofakim: The Outstanding Program",
  "Peace Studies and Conflict Management",
  "Philosophy",
  "Physics",
  "Political Science",
  "Program For Holocaust Studies",
  "Psychology",
  "Sagol Neurobiology",
  "Science Teaching - Biology",
  "Science Teaching - Exact Sciences",
  "Sociology",
  "Social Work",
  "Statistics",
  "Sustainability and Environment Cluster",
  "The History of the People of Israel",
  "The School of Arts Therapy",
  "The School of Criminology",
  "The School of History",
  "Theology",
  "Theater and Performance Studies",
  "Women's and Gender Studies",
];
