export const universities = [
    "Harvard University",
    "Stanford University",
    "Massachusetts Institute of Technology",
    "University of Oxford",
    "University of Cambridge",
    "California Institute of Technology",
    "Yale University",
    "Princeton University",
    "University of Chicago",
    "Columbia University",
    "Imperial College London",
    "University of California, Berkeley",
    "University of Tokyo",
    "ETH Zurich - Swiss Federal Institute of Technology",
    "National University of Singapore",
    "University of Sydney",
    "University of Cape Town",
    "Peking University",
    "University of São Paulo",
    "University of Toronto",
    "University of Melbourne",
    "University of Delhi",
    "Moscow State University",
    "University of Buenos Aires",
    "University of Cape Town",
    "Seoul National University",
    "University of Nairobi",
    "University of Toronto",
    "University of São Paulo",
    "University of Mumbai",
    "Hebrew University of Jerusalem",
    "Tel Aviv University",
    "Technion - Israel Institute of Technology",
    "Weizmann Institute of Science",
    "Ben-Gurion University of the Negev",
    "University of Haifa",
    "Bar-Ilan University",
    "Interdisciplinary Center Herzliya",
    "University of Tel Aviv",
    "Open University of Israel",
    "Ariel University",
    "Sapir Academic College",
    "Sammy Ofer School of Communications at the Interdisciplinary Center Herzliya",
    "Holon Institute of Technology",
    "The Academic College of Tel Aviv-Yafo",
    "Bezalel Academy of Arts and Design",
    "Shenkar College of Engineering, Design, and Art",
    "Ruppin Academic Center",
    "The Academic College of Tel Aviv-Jaffa",
    "Galilee International Management Institute",
    "Hadassah Academic College Jerusalem",
    "The Academic College at Wingate",
    "ORT Braude College of Engineering",
    "Max Stern Academic College of Emek Yezreel",
    "The Academic College of Netanya",
    "Gordon College of Education",
    "The Jerusalem College of Technology - Lev Academic Center",
    "Kinneret Academic College on the Sea of Galilee",
    "Lander Institute - Jerusalem Academic Center",
    "College of Management Academic Studies",
    "Emeq Yezreel College",
    "The College of Law and Business",
    "Israel College of the Bible",
    "Rabbinical College of America",
    "Yezreel Valley College",
    "Ono Academic College",
    "Reidman College",
    "Rishon LeZion College of Management",
    "Western Galilee College",
    "Azrieli College of Engineering Jerusalem",
    "Haredi College of Jerusalem",
    "Haredi College of Tzfat",
    "Haredi College of Betar Illit",
    "The College for Academic Studies Or Yehuda",
    "Haredi College of Kiryat Ono",
    "Ramat Gan College",
    "Ramat Negev College",
    "Geder HaYeSHEVa",
    "Jordan Valley College",
    "Rak Tel Hai College",
    "Academic College of Ashkelon",
    "Academic Center for Law and Science - Ramat Gan",
    "Be'er Ya'akov Talmudic Seminary",
    "Haredi College of Petach Tikva",
    "Haredi College of Acco",
    "Lander Institute Jerusalem",
    "Haredi College of Rehovot",
    "Oranim Academic College",
    "Y. Ram College of Tel Aviv",
    "Tishreen College - The Academic College of the Jezreel Valley",
    "Kfar HaHoresh College",
    "Academic College of Tel Aviv-Jaffa",
    "Sha'arei Mishpat College",
    "Talpiot College of Education",
    "College of Law and Business - Ramat Gan",
    "Pardes Institute of Jewish Studies",
    "Mirrer Yeshiva Cent Institute for Torah and Academics",
    "The Tel Aviv Academic College of Engineering",
    "Emuna College",
    "Torah Lishma Institute",
    "Machon Lev Academic College of Technology",
    "Bezalel Academy of Art and Design Jerusalem",
    "Lander Institute",
    "The College of Administration",
    "Lander Institute Jerusalem",
    "Haredi College of Tzfat",
    "Lander Institute",
    "Netanya Academic College",
    "Sami Shamoon College of Engineering",
    "Kefar Sava Academic College",
    "Jerusalem College of Technology - Lev Academic Center",
    "Ateret Torah College",
    "The College of Law and Business - Ramat Gan",
    "Azrieli College of Engineering Jerusalem",
    "Lander Institute",
    "Hebron Yeshiva",
    "Haredi College of Betar Illit",
    "Yigal Allon Academic College",
    "Emuna College",
    "The Jerusalem Academy of Music and Dance",
    "Braude College of Engineering",
    "The College of Management Academic Studies",
    "Ono Academic College",
    "Ateret Torah College",
    "Azrieli College of Engineering Jerusalem",
    "Yigal Allon Academic College",
    "Ateret Torah College",
    "Azrieli College of Engineering Jerusalem",
    "Haredi College of Betar Illit",
    "Yigal Allon Academic College",
    "Jerusalem College of Technology - Lev Academic Center",
    "The Jerusalem Academy of Music and Dance",
    "Emuna College",
        "University of Oxford",
        "University of Cambridge",
        "Imperial College London",
        "University of Edinburgh",
        "University of London",
        "University of Paris",
        "Sorbonne University",
        "Ecole Polytechnique",
        "University of Munich",
        "University of Heidelberg",
        "University of Zurich",
        "University of Amsterdam",
        "University of Copenhagen",
        "University of Stockholm",
        "University of Helsinki",
        "University of Vienna",
        "University of Rome La Sapienza",
        "University of Barcelona",
        "University of Athens",
        "University of Lisbon",
        "University of Warsaw",
        "Charles University in Prague",
        "University of Budapest",
        "University of Vienna",
        "University of Zurich",
        "University of Oslo",
        "University of Geneva",
        "University of Dublin",
        "University of Brussels",
        "University of Madrid",
        "University of Vienna",
        "University of Warsaw",
        "University of Lisbon",
        "University of Prague",
        "University of Budapest",
        "University of Vienna",
        "University of Zurich",
        "University of Oslo",
        "University of Geneva",
        "University of Dublin",
        "University of Brussels",
        "University of Madrid",
        "University of Copenhagen",
        "University of Stockholm",
        "University of Helsinki",
        "University of Vienna",
        "University of Rome La Sapienza",
        "University of Barcelona",
        "University of Athens",
        "University of Lisbon",
        "University of Warsaw",
        "Charles University in Prague",
        "University of Budapest",
        "University of Vienna",
        "University of Zurich",
        "University of Oslo",
        "University of Geneva",
        "University of Dublin",
        "University of Brussels",
        "University of Madrid",
        "University of Copenhagen",
        "University of Stockholm",
        "University of Helsinki",
        "University of Vienna",
        "University of Rome La Sapienza",
        "University of Barcelona",
        "University of Athens",
        "University of Lisbon",
        "University of Warsaw",
        "Charles University in Prague",
        "University of Budapest",
        "University of Vienna",
        "University of Zurich",
        "University of Oslo",
        "University of Geneva",
        "University of Dublin",
        "University of Brussels",
        "University of Madrid",
        "University of Copenhagen",
        "University of Stockholm",
        "University of Helsinki",
        "University of Vienna",
        "University of Rome La Sapienza",
        "University of Barcelona",
        "University of Athens",
        "University of Lisbon",
        "University of Warsaw",
        "Charles University in Prague",
        "University of Budapest",
        "University of Vienna",
        "University of Zurich",
        "University of Oslo",
        "University of Geneva",
        "University of Dublin",
        "University of Brussels",
        "University of Madrid",
        "University of Copenhagen",
        "University of Stockholm",
        "University of Helsinki",
        "University of Vienna",
        "University of Rome La Sapienza",
        "University of Barcelona",
        "University of Athens",
        "University of Lisbon",
        "University of Warsaw",
        "Charles University in Prague",
        "University of Budapest",
        "University of Vienna",
        "University of Zurich",
        "University of Oslo",
        "University of Geneva",
        "University of Dublin",
        "University of Brussels",
        "University of Madrid",
        "University of Copenhagen",
        "University of Stockholm",
        "University of Helsinki",
        "University of Vienna",
        "University of Rome La Sapienza",
        "University of Barcelona",
        "University of Athens",
        "University of Lisbon",
        "University of Warsaw",
        "Charles University in Prague",
        "University of Budapest",
        "University of Vienna",
        "University of Zurich",
        "University of Oslo",
        "University of Geneva",
        "University of Dublin",
        "University of Brussels",
        "University of Madrid",
        "University of Copenhagen",
        "University of Stockholm",
        "University of Helsinki",
        "University of Vienna",
        "University of Rome La Sapienza",
        "University of Barcelona",
        "University of Athens",
        "University of Lisbon",
        "University of Warsaw",
        "Charles University in Prague",
        "University of Budapest",
        "University of Vienna",
        "University of Zurich",
        "University of Oslo",
        "University of Geneva",
        "University of Dublin",
        "University of Brussels",
        "University of Madrid",
        "University of Copenhagen",
        "University of Stockholm",
        "University of Helsinki",
        "University of Vienna",
        "University of Rome La Sapienza",
        "University of Barcelona",
        "University of Athens",
        "University of Lisbon",
        "University of Warsaw",
        "Charles University in Prague",
        "University of Budapest",
        "University of Vienna",
        "University of Zurich",
        "University of Oslo",
        "University of Geneva",
        "University of Dublin",
        "University of Brussels",
        "University of Madrid",
        "University of Copenhagen",
        "University of Stockholm",
        "University of Helsinki",
        "University of Vienna",
        "University of Rome La Sapienza",
        "University of Barcelona",
        "University of Athens",
        "University of Lisbon",
        "University of Warsaw",
        "Charles University in Prague",
        "University of Budapest",
        "University of Vienna",
        "University of Zurich",
        "University of Oslo",
        "University of Geneva",
        "University of Dublin",
        "University of Brussels",
        "University of Madrid",
        "University of Copenhagen",
        "University of Stockholm",
        "University of Helsinki",
        "University of Vienna",
        "University of Rome La Sapienza",
        "University of Barcelona",
        "University of Athens",
        "University of Lisbon",
        "University of Warsaw",
        "Charles University in Prague",
        "University of Budapest",
        "University of Vienna",
        "University of Zurich",
        "University of Oslo",
        "University of Geneva",
        "University of Dublin",
        "University of Brussels",
        "University of Madrid",
        "University of Copenhagen",
        "University of Stockholm",
        "University of Helsinki"
]